### ISSUE TITLE
[BUG] Un flow `last_positions` a bloqué les autres flow prefect pendant 20 minutes

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1113]
J'ai du annuler flow et les autres flows créées pour que ça reparte

**Comment by louptheron** [comment]
Les autres flows sont en attente, meêm equand je veux les cancel, ça reste en cancelling.

```
Failed to retrieve task state with error: ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='host.docker.internal', port=4200): Read timed out. (read timeout=15)"))
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='host.docker.internal', port=4200): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/prefect/engine/cloud/task_runner.py", line 154, in initialize_run
    task_run_info = self.client.get_task_run_info(
  File "/opt/venv/lib/python3.8/site-packages/prefect/client/client.py", line 1803, in get_task_run_info
    result = self.graphql(mutation)  # type: Any
  File "/opt/venv/lib/python3.8/site-packages/prefect/client/client.py", line 549, in graphql
    result = self.post(
  File "/opt/venv/lib/python3.8/site-packages/prefect/client/client.py", line 452, in post
    response = self._request(
  File "/opt/venv/lib/python3.8/site-packages/prefect/client/client.py", line 739, in _request
    response = self._send_request(
  File "/opt/venv/lib/python3.8/site-packages/prefect/client/client.py", line 603, in _send_request
    response = session.post(
  File "/opt/venv/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='host.docker.internal', port=4200): Read timed out. (read timeout=15)
```

**Comment by louptheron** [comment]
J'ai l'impression qu'ils se sont cancel au bout de 15mn (grace au flow healtcheck), on peut baisser cette valeur à genre 5 minutes ?
