### ISSUE TITLE
Prefect - Le flow des Contrôles est cassé

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2186]
En intégration, bloque la MEP ?

Cf. http://prefect-test.csam.e2.rie.gouv.fr/default/flow-run/d3b130ed-2314-4b8b-a545-dfd706bb2a9a?overview

```
Task 'load_missions_and_missions_control_units': Exception encountered during task execution!
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/opt/venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "<string>", line 663, in load_missions_and_missions_control_units
  File "/home/monitorfish-pipeline/datascience/src/pipeline/generic_tasks.py", line 160, in load
    df = prepare_df_for_loading(
  File "/home/monitorfish-pipeline/datascience/src/pipeline/processing.py", line 497, in prepare_df_for_loading
    df_[pg_array_columns] = df_values_to_psql_arrays(
  File "/home/monitorfish-pipeline/datascience/src/pipeline/processing.py", line 353, in df_values_to_psql_arrays
    return df.applymap(serialize, na_action="ignore").fillna("{}")
  File "/opt/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4459, in fillna
    return super().fillna(
  File "/opt/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 6424, in fillna
    new_data = self._mgr.fillna(
  File "/opt/venv/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 621, in fillna
    return self.apply(
  File "/opt/venv/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 427, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/venv/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 1918, in fillna
    values = values.fillna(value=value, limit=limit)
  File "/opt/venv/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 1692, in fillna
    new_codes = self._validate_setitem_value(value)
  File "/opt/venv/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 1893, in _validate_setitem_value
    raise ValueError(
ValueError: Cannot setitem on a Categorical with a new category, set the categories first
```

**Comment by VincentAntoine** [comment]
Nope, c'est dû au fait qu'il n'y a pas de contrôles dans le dernier mois en intégration et qu'une tâche du flow ne supporte pas d'avoir un DataFrame vide en entrée. Ca n'est pas gênant, car quand il n'y a pas de contrôles à importer dans la période sélectionnée alors il n'y a rien à faire donc on se moque que le flow fail. Et surtout ce flow est voué à disparaître suite au switch vers MF donc RAF.
