### ISSUE TITLE
Lorsque je lance l'application en `dev`, le build `tsc` fail

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2220]
## Erreur

Je ne peux plus lancer le frontend avec `make run-frontend`.

L'erreur est identifiée : 
- https://github.com/microsoft/TypeScript/issues/54549
- https://github.com/microsoft/TypeScript/issues/52046

Stacktrace :
```
RangeError: Maximum call stack size exceeded
    at isReachableFlowNodeWorker (/home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:66679:39)
    at isReachableFlowNodeWorker (/home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:66689:79)
    at /home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:66715:48
    at some (/home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:472:15)
    at isReachableFlowNodeWorker (/home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:66715:18)
    at isReachableFlowNodeWorker (/home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:66689:79)
    at /home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:66715:48
    at some (/home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:472:15)
    at isReachableFlowNodeWorker (/home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:66715:18)
    at isReachableFlowNodeWorker (/home/lth/workspace/monitorfish/frontend/node_modules/typescript/lib/typescript.js:66689:79)
```
## Fix temporaire

Le fix temporaire est de faire en sorte qu'une exception n'arrête pas le process de `react-scripts`, dans le fichier `frontend/node_modules/react-scripts/scripts/start.js` je commente `throw err;` :
```
// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', err => {
  // throw err;
});
```

Cela permet de runner l'application mais ne permet toujours pas de faire fonctionner le linter/typing ts (et donc husky)

## TODO

Il faudrait debugger (cf. https://github.com/microsoft/TypeScript/issues/40819#issuecomment-700379873) pour comprendre l'origine de l'erreur

**Comment by louptheron** [comment]
@Jolg42 En effet la MAJ de TS avait résolu ce souci !
Merci pour ta suggestion, je n'avais pas vu ton commentaire.

**Comment by Jolg42** [comment]
Super 💯
