### ISSUE TITLE
[BUG] Le flow `Notify malfunction` est cassé

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2254]
http://prefect.csam.e2.rie.gouv.fr/default/flow-run/7f989de1-0282-4a84-a018-dd187e4c9920

```
 14:32:17
ERROR
CloudTaskRunner
Task 'FilterTask': Exception encountered during task execution!
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/opt/venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/opt/venv/lib/python3.8/site-packages/prefect/tasks/control_flow/filter.py", line 81, in run
    filtered = [r for r in task_results if self.filter_func(r)]
TypeError: 'NoneType' object is not iterable
```

**Comment by VincentAntoine** [comment]
Vu, c'est pas vraiment un plantage du flow, c'est que quand on skip le run (par exemple parce qu'il y a déjà un run en cours), une des tâches génériques utilisées lève une erreur au lieu d'être skippée comme toutes les autres. Faut changer la valeur par défaut de `skip_on_upstream_skip`.
