### ISSUE TITLE
On retrouve régulierement des OOM errors dans les logs backend

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2277]
http://csam-kibana.csam.e2.rie.gouv.fr/elk/s/journaux/app/kibana#/discover/doc/81749390-aee7-11e9-8e68-1dbaacdb0983/logs-2023.06.30-001073?id=lIniDokB1FMqlM-Xb6o6&_g=()

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.OutOfMemoryError: Java heap space] with root cause
java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringLatin1.newString(StringLatin1.java:769) ~[?:?]
	at java.lang.String.substring(String.java:2710) ~[?:?]
	at org.springframework.boot.loader.jar.StringSequence.toString(StringSequence.java:154) ~[monitorfish-v1.30.1-exec.jar:v1.30.1]
	at org.springframework.boot.loader.jar.JarURLConnection$JarEntryName.toString(JarURLConnection.java:358) ~[monitorfish-v1.30.1-exec.jar:v1.30.1]
	at org.springframework.boot.loader.jar.JarURLConnection.get(JarURLConnection.java:263) ~[monitorfish-v1.30.1-exec.jar:v1.30.1]
	at org.springframework.boot.loader.jar.Handler.openConnection(Handler.java:89) ~[monitorfish-v1.30.1-exec.jar:v1.30.1]
	at java.net.URL.openConnection(URL.java:1094) ~[?:?]
	at jdk.internal.loader.URLClassPath$Loader.getResource(URLClassPath.java:653) ~[?:?]
	at jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:322) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:424) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.security.AccessController.executePrivileged(AccessController.java:807) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149) ~[monitorfish-v1.30.1-exec.jar:v1.30.1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectJavaClassFinderKt.tryLoadClass(ReflectJavaClassFinder.kt:49) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClassFinder.findKotlinClass(ReflectKotlinClassFinder.kt:34) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClassFinder.findKotlinClassOrContent(ReflectKotlinClassFinder.kt:38) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope$classes$1.invoke(LazyJavaPackageScope.kt:67) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope$classes$1.invoke(LazyJavaPackageScope.kt:59) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope.findClassifier(LazyJavaPackageScope.kt:146) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope.getContributedClassifier(LazyJavaPackageScope.kt:136) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.JvmPackageScope.getContributedClassifier(JvmPackageScope.kt:55) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.ChainedMemberScope.getContributedClassifier(ChainedMemberScope.kt:35) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.descriptors.FindClassInModuleKt.findClassifierAcrossModuleDependencies(findClassInModule.kt:26) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.computeClassifierDescriptor(TypeDeserializer.kt:268) ~[kotlin-reflect-1.8.22.jar!/:1.8.22-release-407(1.8.22)]
```

**Comment by louptheron** [comment]
N'apparait plus
