### ISSUE TITLE
Upgrades du build et de l'environnement python

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#2625]
- [x] Montée de version python et de toutes les dépendances
- [x] Utiliser poetry dans le build de l'image
- [x] Optimiser le build (multi stage)
- [x] Optimiser l'utilisation du cache dans la CI

**Comment by louptheron** [comment]
@VincentAntoine Je n'arrive pas à déployer la pipeline en intégration :
```
docker.pkg.github.com/mtes-mct/monitorfish/monitorfish-pipeline:v1.38.0
Traceback (most recent call last):
  File "/home/monitorfish-pipeline/datascience/main.py", line 4, in <module>
    from src.pipeline.flows_config import flows_to_register
  File "/home/monitorfish-pipeline/datascience/src/pipeline/flows_config.py", line 301, in <module>
    flow.storage = Local(
                   ^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/prefect/storage/local.py", line 62, in __init__
    os.makedirs(abs_directory, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/monitorfish-pipeline/.prefect/flows'
make: *** [Makefile:87 : register-pipeline-flows-int] Erreur 1

```
