### ISSUE TITLE
EntityConversionException: Error while converting 'LogbookMessage`

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3904]
Sentry Issue: [MONITORFISH-14C](https://sentry.incubateur.net/organizations/betagouv/issues/134092/?referrer=github_integration)

`NoSuchElementException: Message type NOT-COE not found`:

```
NoSuchElementException: Collection contains no element matching the predicate.
    at fr.gouv.cnsp.monitorfish.domain.entities.logbook.LogbookMessageTypeMapping$Companion.getClassFromName(LogbookMessageTypeMapping.kt:57)
    at fr.gouv.cnsp.monitorfish.domain.mappers.ERSMapper.getERSMessageValueFromJSON(ERSMapper.kt:27)
    at fr.gouv.cnsp.monitorfish.infrastructure.database.entities.LogbookReportEntity.toLogbookMessage(LogbookReportEntity.kt:110)
    at fr.gouv.cnsp.monitorfish.infrastructure.database.repositories.JpaLogbookReportRepository.findAllMessagesByTripNumberBetweenDates(JpaLogbookReportRepository.kt:279)
    at jdk.internal.reflect.GeneratedMethodAccessor944.invoke
...
(95 additional frame(s) were not displayed)

NoSuchElementException: Message type NOT-COE not found
    at fr.gouv.cnsp.monitorfish.domain.entities.logbook.LogbookMessageTypeMapping$Companion.getClassFromName(LogbookMessageTypeMapping.kt:50)
    at fr.gouv.cnsp.monitorfish.domain.mappers.ERSMapper.getERSMessageValueFromJSON(ERSMapper.kt:27)
    at fr.gouv.cnsp.monitorfish.infrastructure.database.entities.LogbookReportEntity.toLogbookMessage(LogbookReportEntity.kt:110)
    at fr.gouv.cnsp.monitorfish.infrastructure.database.repositories.JpaLogbookReportRepository.findAllMessagesByTripNumberBetweenDates(JpaLogbookReportRepository.kt:279)
    at jdk.internal.reflect.GeneratedMethodAccessor944.invoke
...
(95 additional frame(s) were not displayed)

EntityConversionException: Error while converting 'LogbookMessage'. {"faoZoneEntered": "87.2.6", "latitudeEntered": 36.0, "longitudeEntered": -39.25, "effortZoneEntered": "E", "economicZoneEntered": "XIN", "targetSpeciesOnEntry": "PELAGIC", "effortZoneEntryDatetimeUtc": "2024-11-02T03:15:00Z", "statisticalRectangleEntered": null}
    at fr.gouv.cnsp.monitorfish.domain.mappers.ERSMapper.getERSMessageValueFromJSON(ERSMapper.kt:34)
    at fr.gouv.cnsp.monitorfish.infrastructure.database.entities.LogbookReportEntity.toLogbookMessage(LogbookReportEntity.kt:110)
    at fr.gouv.cnsp.monitorfish.infrastructure.database.repositories.JpaLogbookReportRepository.findAllMessagesByTripNumberBetweenDates(JpaLogbookReportRepository.kt:279)
    at jdk.internal.reflect.GeneratedMethodAccessor944.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
(95 additional frame(s) were not displayed)

Invocation failure
Controller [fr.gouv.cnsp.monitorfish.infrastructure.api.bff.VesselController]
Method [public fr.gouv.cnsp.monitorfish.infrastructure.api.outputs.VoyageDataOutput fr.gouv.cnsp.monitorfish.infrastructure.api.bff.VesselController.getVesselLogbookMessages(java.lang.String,fr.gouv.cnsp.monitorfish.domain.use_cases.dtos.VoyageRequest,java.lang.String)] with argument values:
 [0] [type=java.lang.String] [value=IRL000I13000],
[1] [type=fr.gouv.cnsp.monitorfish.domain.use_cases.dtos.VoyageRequest] [value=LAST],
[2] [type=java.lang.String] [value=20240089] 
```

**Comment by louptheron** [comment]
à vérifier en PROD
