### ISSUE TITLE
MissingFieldException: Field 'note' is required for type with serial name 'fr.gouv.cnsp.monitorfish.infrastructure.api.i...

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3906]
Sentry Issue: [MONITORFISH-151](https://sentry.incubateur.net/organizations/betagouv/issues/134197/?referrer=github_integration)

```
MissingFieldException: Field 'note' is required for type with serial name 'fr.gouv.cnsp.monitorfish.infrastructure.api.input.LogbookPriorNotificationFormDataInput', but it was missing
    at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
    at fr.gouv.cnsp.monitorfish.infrastructure.api.input.LogbookPriorNotificationFormDataInput.<init>(LogbookPriorNotificationFormDataInput.kt:5)
    at fr.gouv.cnsp.monitorfish.infrastructure.api.input.LogbookPriorNotificationFormDataInput$$serializer.deserialize(LogbookPriorNotificationFormDataInput.kt:5)
    at fr.gouv.cnsp.monitorfish.infrastructure.api.input.LogbookPriorNotificationFormDataInput$$serializer.deserialize(LogbookPriorNotificationFormDataInput.kt:5)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
...
(95 additional frame(s) were not displayed)

MissingFieldException: Field 'note' is required for type with serial name 'fr.gouv.cnsp.monitorfish.infrastructure.api.input.LogbookPriorNotificationFormDataInput', but it was missing at path: $
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
    at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
    at org.springframework.http.converter.KotlinSerializationStringHttpMessageConverter.readInternal(KotlinSerializationStringHttpMessageConverter.java:64)
    at org.springframework.http.converter.KotlinSerializationStringHttpMessageConverter.readInternal(KotlinSerializationStringHttpMessageConverter.java:45)
    at org.springframework.http.converter.AbstractKotlinSerializationHttpMessageConverter.read(AbstractKotlinSerializationHttpMessageConverter.java:104)
...
(95 additional frame(s) were not displayed)

Could not read kotlinx.serialization.json.Json$Default@633b0d9a: Field 'note' is required for type with serial name 'fr.gouv.cnsp.monitorfish.infrastructure.api.input.LogbookPriorNotificationFormDataInput', but it was missing at path: $
```

**Comment by louptheron** [comment]
J'attends de voir si ce bug réapparait avant de creuser.

**Comment by louptheron** [comment]
ne réapparait pas
